name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      PACKAGE_BASEURL: https://download.zerotier.com/debian/buster/pool/main/z/zerotier-one/
      ARCH: amd64
      VERSION1: 1.6.6
      VERSION2: 1.8.1 # checkout actual branch to test here
      NWID: c7c8172af150e770


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # - name: get curl
      #   run: sudo apt-get install curl -y

      - name: run
        run: sudo $GITHUB_WORKSPACE/script.sh
